// Whether Apple's captured records are on disk, decided once for both crates
// that read them.
//
// `include!`d by `reims-vgpu-wire/build.rs` and `reims-vgpu/build.rs` rather
// than copied, because the facts here — the directory override, the two file
// names, and what `REIMS_WIRE_FIXTURES_REQUIRED` means — must not fork between
// the two suites that stand down without them. A build-dependency crate for
// twenty lines would cost more than it carries, and a build script has no
// smaller unit to share from.
//
// It sits beside the capture harness that writes the files it looks for, which
// is the one directory where "what the oracle produces and where" is already
// the subject. It is not compiled into either crate — build scripts include it.

/// Emit `wire_fixtures` and `wire_inventory` for whichever oracle outputs exist.
///
/// Presence is a **build-time** fact so the tests that need it can carry
/// `#[cfg_attr(not(wire_fixtures), ignore = "…")]` and libtest can print
/// `ignored` for each one. That is the whole point of doing it here: the
/// arrangement this replaces returned early inside each test body, so 36 tests
/// that measured nothing reported `ok` in 0.00 s across two crates — the only
/// layout-truth tests in the project, reading exactly like coverage on every
/// checkout without the fixtures.
///
/// The two outputs are probed separately so a stale capture is distinguishable
/// from a missing one: `inventory.json` is regenerated by
/// `wire-oracle.sh --inventory` and `fixtures.json` by the sweep, and having one
/// without the other is a normal intermediate state that should stand down only
/// the tests that read the absent half.
fn probe_wire_fixtures(default_dir: &str) {
    println!("cargo:rerun-if-env-changed=REIMS_WIRE_FIXTURES_DIR");
    println!("cargo:rerun-if-env-changed=REIMS_WIRE_FIXTURES_REQUIRED");
    println!("cargo:rustc-check-cfg=cfg(wire_fixtures)");
    println!("cargo:rustc-check-cfg=cfg(wire_inventory)");

    let dir = std::env::var("REIMS_WIRE_FIXTURES_DIR").unwrap_or_else(|_| default_dir.to_string());
    let required = std::env::var("REIMS_WIRE_FIXTURES_REQUIRED").is_ok();

    let mut absent = false;

    for (file, cfg) in [
        ("fixtures.json", "wire_fixtures"),
        ("inventory.json", "wire_inventory"),
    ] {
        let path = format!("{dir}/{file}");
        if std::path::Path::new(&path).is_file() {
            println!("cargo:rerun-if-changed={path}");
            println!("cargo:rustc-cfg={cfg}");
        } else if required {
            // The runtime assertion this replaces cannot fire any more — an
            // ignored test never runs to check it — so failing the build is
            // what keeps REQUIRED meaning "these must have run".
            panic!(
                "REIMS_WIRE_FIXTURES_REQUIRED is set but there is no {file} at \
                 {dir}; regenerate with scripts/wire-oracle/wire-oracle.sh"
            );
        } else {
            absent = true;
        }
    }

    if absent {
        // Watch the *containing directory* for the outputs that are not there
        // yet, never the absent file by name. Cargo cannot stat a missing
        // watched path, reads that as changed, and so marks the build script
        // dirty on every single build — and since a dependent's fingerprint
        // includes its build script's, naming an absent file here recompiled
        // this crate, `reims-vgpu` and `reims-vgpu-paging` on every invocation
        // on every checkout without the fixtures, which is every non-Apple one.
        // A directory's recorded mtime moves when a file is created inside it,
        // so watching the nearest one that exists keeps the property the
        // by-name watch was for: a capture taken after a build is picked up
        // without a manual touch. Climb at most one level, so a
        // REIMS_WIRE_FIXTURES_DIR pointing into a tree that does not exist
        // watches nothing rather than walking some huge ancestor.
        let dir = std::path::Path::new(&dir);
        let watch = if dir.is_dir() {
            Some(dir)
        } else {
            dir.parent().filter(|parent| parent.is_dir())
        };
        if let Some(watch) = watch {
            println!("cargo:rerun-if-changed={}", watch.display());
        }
    }
}
